mixer = []
mixer.append('Yamaha')
mixer.append('DiGiCo')
mixer.append('Profile')
mixer.append('Allen&Heath')
mixer.append('Roland')
mixer.append('SSL')
mixer.append('LV1')
print(mixer)
print(mixer[3])
print(mixer[-1])
mixer.insert(3,'Behringer')
print(mixer)
del mixer[1]
print(mixer)
waves_mixer = mixer.pop()
print(mixer)
print(waves_mixer)
mixer.append('DiGiCo')
mixer.append('LV1')
print(sorted(mixer))
print(mixer)
print(sorted(mixer, reverse=True))
print(mixer)
print("i am use", len(mixer), "digital consoles on the my job." )
